source 'https://rubygems.org'

gem 'csv'
gem 'dotenv'
gem 'gmail'
gem 'mail'
gem 'rack', '~> 2.0.1'
gem 'rspec'
gem 'highline', '>= 1.5.1', group: :test
gem 'google_drive'
gem 'json'
gem 'rake', '< 11.0'
gem 'rspec', '~> 3.4'
gem 'rubocop', '~> 0.57.2'
gem 'pry'
gem 'nokogiri'
gem 'google-api-client'